# Generated by Django 4.2.4 on 2025-07-30 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mailer_campaign',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mailer.campaign')),
            ],
            options={
                'db_table': 'mailer_email',
                'unique_together': {('email_address', 'campaign_id')},
            },
        ),
    ]
