# Generated by Django 4.2.4 on 2025-01-28 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email_address', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mailer.campaign')),
            ],
        ),
    ]
