# Generated by Django 5.1.4 on 2024-12-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='email',
            name='question_text',
        ),
        migrations.AddField(
            model_name='email',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
