version: '3.8'

services:
  # Main application service (Django + Streamlit)
  app:
    build: .
    ports:
      - "8000:8000"  # Django API
      - "8501:8501"  # Streamlit Frontend
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=email_sender.settings
      - DATABASE_NAME=email_campaign_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_HOST_USER=your-email@gmail.com
      - EMAIL_HOST_PASSWORD=your-app-password
    depends_on:
      - db
    restart: unless-stopped

  # Database service
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=email_campaign_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Redis for caching (optional)
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
