# Generated by Django 4.2.4 on 2025-07-30 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
    ]
