# Generated by Django 4.2.4 on 2025-08-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_emailtemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='campaign_id',
            new_name='campaign',
        ),
        migrations.AlterUniqueTogether(
            name='email',
            unique_together={('email_address', 'campaign')},
        ),
    ]
